---
title: "R Project"
listing: posts
site: distill::distill_website
---

Here is some of my project using R. I would love to hear if you found them helpful. Or, if there’s a mistake you find or a suggestion you have, I’d love to hear about those, too.

## S&P 500 Profit Prediction

For this project, we try to predict the profitability of the S&P500 Companies and pick the company with the highest chance to generate profit. So far, in 2021, our top 20 companies have the profitability of 47.25%, which is far higher than the normal S&P 500's profit of 23.07%. 

You can check it out [here](https://sp500predictionprofit.netlify.app)

Moreover, if you want to see the powerpoint presentation for the project, I also included it below [here](https://docs.google.com/presentation/d/1acwePWvIieVakPHu-R3zLfViFH8QpYD3/edit?usp=sharing&ouid=107416410399851833560&rtpof=true&sd=true)

## Bayesian Finance

For this project, we try a different method: using Bayesian Technique to predict the earnings of S&P 500 Companies. How will the project turn out? You can check it out [here](https://nolan-meyer.github.io/bayesian-finance/) 

## Exploration of Rayshader

This project focuses on discovering rayshader features (the 3D Mapping technique in R).

What is Rayshader? rayshader is an open source package for producing 2D and 3D data visualizations in R. rayshader uses elevation data in a base R matrix and a combination of raytracing, spherical texture mapping, overlays, and ambient occlusion to generate beautiful topographic 2D and 3D maps. In addition to maps, rayshader also allows the user to translate ggplot2 objects into beautiful 3D data visualizations.

In this project, we will see different feautures of rayshader, how to combine that with ggplot2 as well as a cool dataset for you to explore!

Here is the link to the [website](https://rayshader.netlify.app/)

## Change in Stock market before and After the Pandemic

This project focuses on finding  the differences between different companies within the top 3 of every sector in the S&P 500 to see which company thrives and which company falls after the pandemic. We track its market cap, volume, price per share to see the key differences between these 11 fields.

Here is the link to the [website](https://data-science-final-project.netlify.app)