---
title: "A really cool graph"
description: |
  A short description of the post.
author:
  - name: DucNgo
    url: {}
date: 10-19-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
library(janitor)       # for cleaning variable names
theme_set(theme_minimal()) # My favorite ggplot() theme :)
```

```{r, fig.height= 10, fig.width= 6}
georgia_pop <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-16/georgia_pop.csv')
georgia_pop %>% 
  pivot_longer(cols = Colored: White, 
               names_to = "Colored_white",
               values_to = "Percent") %>% 
  ggplot(aes(y = Year, x = Percent)) + 
  geom_path(aes(linetype=Colored_white)) + 
  scale_x_reverse(breaks = seq(0,100,5)) + 
  scale_y_continuous(breaks = seq(1790, 1890,10)) + 
  scale_linetype_discrete(name = "", labels = c("Colored                                                                                                           ", "White")) + 
  labs(title = "Comparative Increase Of White And Colored \n Population Of Georgia",
       color = "",
       y = "", 
       x = "Percents")+ 
  theme_minimal() + 
  theme(plot.title = element_text(color = "black", size = 15, face = "bold", hjust = 0.5),
        legend.position = "bottom", 
        plot.background = element_rect(fill = "blanchedalmond"),
        panel.grid.major = element_line(size = 0.2, linetype = 'solid',
                                colour = "coral3"),
        panel.grid.minor = element_line(size = 0, linetype = 'solid',
                                colour = "coral3"),
        legend.title = element_blank()) 
```




